### PR TITLE
Improve the per user workflow for everyone

### PR DESCRIPTION
**Pull request by CatsArmy**
Updates the .gitignore to ignore all .user files expect for the *.template.*.user
added a template.user and a .user for the .props common file

### CODE REVIEW

**Comment by Scyye** [comment]
have you verified this functions on a fresh clone?

**Comment by CatsArmy** [comment]
yep you can build and all
only thing is before you can start building for the first time you need to follow the instructions in the Common\CommonSettings.template.props.user

which are all done in the "Common" folder:
copy CommonSettings.template.props.user
paste and rename it to:
Common\CommonSettings.props.user

within the "Common\CommonSettings.props.user" file you just created/pasted
replace the {RoundsFolder} with the path to your Rounds folder(e.g. C:\Program Files (x86)\Steam\steamapps\common\ROUNDS)
and aslong as you dont do that in the .template file your fine.
from now on the "Common\CommonSettings.props.user" file will stay there even between branches on your pc

**Comment by Scyye** [comment]
aalund what the hell are you doing

**Comment by Scyye** [comment]
@AALUND13 from now on, use a fork of this on your own personal github.

**Comment by AALUND13** [comment]
Lol, this @CatsArmy PR not My.

**Comment by AALUND13** [comment]
Also why do you not like me Merging this to my own branch, I am not trying be mean just a question

**Comment by Scyye** [comment]
because theres no reason to, it should just be merged into the rwf branch

**Comment by AALUND13** [comment]
This is also my first time contributing to a project, I mainly work on my own projects alone.

**Comment by Scyye** [comment]
okay, so now i made it so you cant accidentally do anything, there shouldnt be any other issue.

**Pull request merged**
